### ISSUE TITLE
三星 Galaxy Note4 翻车三星 Galaxy Note4 翻车

### ISSUE THREAD

**Issue by 1280103995** [xuhongv/TakePhotoAndroidN-master#1]
从相册选择图片的时候，没有用裁剪功能时，就闪退。
BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/DCIM/Camera/20180615_131203.jpg: open failed: ENOENT (No such file or directory)

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=262246, result=-1, data=Intent { dat=content://media/external/images/media/42887 flg=0x1 (has extras) }} to activity {cn.zac.it.loan/cn.zac.it.upload.ui.activity.UploadActivity}: java.lang.IllegalArgumentException: quality must be 0..100
                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:4921)
                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4964)
                                                                    at android.app.ActivityThread.access$1600(ActivityThread.java:221)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:158)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                 Caused by: java.lang.IllegalArgumentException: quality must be 0..100
                                                                    at android.graphics.Bitmap.compress(Bitmap.java:1313)

代码错误指向compressImage()中的image.compress(Bitmap.CompressFormat.JPEG, options, baos);

**Comment by 1280103995** [comment]
还有拍出来的照片逆时针旋转了90度

华为手机正常

**Comment by xuhongv** [comment]
你降低下压缩质量；
